### ISSUE TITLE
Set up bug mirror to Google's internal bug tracker

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/k8s-config-connector#1175]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

Google has an issue tracking system, and we track internal work in it.  But in general, for KCC, we want to encourage issues to be filed here and worked on "in the open".

The task is to set up issue mirror so that we can open issues here on github and still have them appear in Google's internal systems, so we can track work here coherently with internal work.

**Comment by ldanielmadariaga** [comment]
This item has been open for >12 months. As part of scheduled repository maintenance, this Issue/PR will be closed. If this is still a critical ask, please re-open and work with your Google Cloud Account team to prioritize it with GCP KCC Product Management.
