### ISSUE TITLE
tracking issue: cluster & namespace actuation pause

### ISSUE THREAD

**Issue by acpana** [GoogleCloudPlatform/k8s-config-connector#1288]
Working on allowing KCC to pause actuation of resources in GKE by adding a field to the CC & CCC crds.

Here's some pieces of work that need to be done:

* [ ] watch CC / CCC in core KCC
* [ ] (maybe) refactor to have the CC, CCC CRDs outside the operator
* [ ] define a sane default
* [ ] (maybe) define sane default flag and precendence over CC, CCCs values
* [ ] some really solid e2es & integrations: reconcile, pause, reconcile, pause ... ; start in pause and make changes to k8s objects then reconcile, etc.

**Comment by jingyih** [comment]
> (maybe) refactor to have the CC, CCC CRDs outside the operator

My understanding is that they are currently structured by k-d-p convention. But if I am wrong, feel free to refactor.

**Comment by acpana** [comment]
Closing this tracking issue as work has either been done or lives in its own issue as a follow on.
