### ISSUE TITLE
Checklist for our first Direct-Actuation resource

### ISSUE THREAD

**Issue by justinsb** [GoogleCloudPlatform/k8s-config-connector#1681]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

Let's create a checklist for our first direct-actuation resource (LoggingLogMetric)

- [ ] Review directbase_controller for todos
- [ ] Verify pause support
- [ ] Verify abandon-on-delete support
- [ ] Decide behaviour for state-into-spec: merge (do we drop fields?)
- [ ] Create tests for any "difficult" scenarios
- [ ] Create tests 
- [ ] Audit mapping logic - e.g. fields should have a `if foo != nil` check
- [ ] Verify immutability webhook works
- [ ] Verify references to LoggingLogMetric
- [ ] Verify references from LoggingLogMetric
- [ ] Verify IAM

cc @yuwenma  , cc @cheftako   (I think you can both edit this issue to add things to the checklist!)

We could also break this out into bugs, I guess, but that might be overkill!

**Comment by ldanielmadariaga** [comment]
This item has been open for >12 months. As part of scheduled repository maintenance, this Issue/PR will be closed. If this is still a critical ask, please re-open and work with your Google Cloud Account team to prioritize it with GCP KCC Product Management.
