### ISSUE TITLE
LoggingLogMetric direct actuation checklist

### ISSUE THREAD

**Issue by acpana** [GoogleCloudPlatform/k8s-config-connector#1690]
> Copied as a worksheet from https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/1681 but changed it a fair amount

Checklist for LoggingLogMetric (LLM) `direct` actuation. There may be some overlap on items. Not all of these will necessarily be applicable.

#### Code & Reconcilliaiton
- [x] Review directbase_controller for todos
- [x] Audit mapping logic - e.g. fields should have a `if foo != nil` check
- [x] Verify that mutable-but-unreadable fields don't cause (infinite) diffs
- [x] Verify that any custom diffs from the DCL controller are reflected in the direct path 

#### KCC System

- [x] Double check that the user agent is set as `Kcc/controller-manager` (consistent with other controllers) in order for usage telemetry to work

#### CRD
* [x] make sure the CRD is backwards compatible

#### Special Labels/ Directives support
* [x] check that the "special" directives [here](https://cloud.google.com/config-connector/docs/reference/resource-docs/logging/logginglogmetric#custom_resource_definition_properties) continue to be supported

#### General Labels/ Directives support
As taken from: https://github.com/maqiuyujoyce/k8s-config-connector/blob/master/pkg/k8s/constants.go

* [ ] mutable-but-unreadable-fields
* [x] observed-secret-versions
* [ ] supports-ssa
* [ ] blueprint
* [x] management-conflict-prevention-policy
* [x] deletion-policy
* [x] reconcile-interval-in-seconds

##### Container Annotations

* [x] project-id
* [x] folder-id
* [x] organization-id

#### Functional

* [x] pause via CC, CCC or annotations works
* [ ] unmanaging works
* [x] acquisition of resource works
* [x] abandon on delete works
* [x] cascading deletes

#### References
* [x] Check that references in work
* [x] Check that references out work
* [x] Check that IAM references work

#### Immutability
* [x] check that fields that were immutable before, continue to be immutable

#### Webhooks
* [x] check the deletion defender still works
* [x] check that the immutability webhook still works

### Testing
- [x] Create tests for any "difficult" scenarios
- [x] Create tests
  - [x] Field testing
    - [x]  Field set, unmanage and unset

---

#### Enchancements

* [ ] Redacted log for why we are diffing
* [ ] Redacted log for rest requests
* [ ] metrics
  * [ ] reconcile success rate per kind
  * [ ] reconcile time per kind
  * [ ] work queue length

**Comment by acpana** [comment]
* [x] Review directbase_controller for todos

Calling this done as remaining TODOs are either not applicable to LLM specifically for its parity b/w a DCL and direct controller or contain simple refactor work like #1702

**Comment by acpana** [comment]
Calling this "done" as merged in https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1649 and spike proves that we are at parity b/w the DCL and direct version for the behavior of field set, unmanage, unset here.

* [x] Field set, unmanage and unset

**Comment by acpana** [comment]
* [x] Audit mapping logic - e.g. fields should have a if foo != nil check

AFAICT, all the fields have a check for unset intent or are at parity with the DCL controller

**Comment by acpana** [comment]
* [x]  observed-secret-versions

AFAICT, there are no sensitive fields in LoggingLogMetric BUT the directbase controller doesn't handle sensitive fields just yet. https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/1724 to track its addition

**Comment by acpana** [comment]
* [x] acquisition of resource works

Calling this done as per https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1741#issuecomment-2101589817

**Comment by acpana** [comment]
Container Annotations
* [x] project-id
* [x] folder-id
* [x] organization-id


LLM (dcl based) does not support container annotations as there would be an `SupportsContainerAnnotations: true,` in the following:

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/1b48ee4296b7409b75c4c0ec430fe97d0e0dad0b/pkg/dcl/metadata/metadata.go#L527-L531

**Comment by acpana** [comment]
* [x] deletion-policy

`directbase_controller` already honors the `deletion-polic` annotation:

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/1b48ee4296b7409b75c4c0ec430fe97d0e0dad0b/pkg/controller/direct/directbase/directbase_controller.go#L230-L246

> For future conversion we can probably get rid of this requirement or maybe just relegate it to a adding a test!

**Comment by acpana** [comment]
* [x]  cascading deletes

checked by deleting the (new) CRD for LLM

**Comment by gemmahou** [comment]
[x] check that fields that were immutable before, continue to be immutable
PR: https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1750

Add immutability check in llm controller, for fields: spec.metricDescriptor.metricKind and valueType; Add scenario test cases to verify that the direct controller behaves the same as DCL.

**Comment by gemmahou** [comment]
* [x] check that the immutability webhook still works
Local test steps:
1. Create a KRM resource, describe the resource verify it's up to date
2. Update an immutable field and apply
3. The operation fails as expected, example console output: https://screenshot.googleplex.com/3rf8557eTCqx2Fn.png

* [x] check the deletion defender still works
Local test steps: 
1. Create a KRM resource, describe the resource verify it's up to date and check it's created in Cloud Console
4. Delete the CRD logginglogmetrics.logging.cnrm.cloud.google.com
5. Verify that the KRM resource is gone, but GCP resource still exists in Cloud Console

**Comment by acpana** [comment]
* [x]  reconcile-interval-in-seconds

Added as part of https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1746

**Comment by acpana** [comment]
* [x] abandon on delete works

Verified in conjunction with deletion defender when uninstalling (by deleting CRD).

**Comment by acpana** [comment]
CRD
* [x]  make sure the CRD is backwards compatible

I ran over a few manual upgrade scenarios that involved:

* installing a pre 1.118 CRD for LoggingLogMetirc
* creating LoggingLogMetric resources
* updating the kcc control plane to sha `c71bec6fb` (post 1.117 release)
* installing the new CRD for LoggingLogMetric
* check controller logs, hand off successful
* modifying existing resources, see changes applied onto GCP/ cloud provider.

**Comment by acpana** [comment]
* [x] pause via CC, CCC or annotations works

manual verification and `pause-tests` pass for this resource!

**Comment by acpana** [comment]
Special Labels/ Directives support
* [x] check that the "special" directives [here](https://cloud.google.com/config-connector/docs/reference/resource-docs/logging/logginglogmetric#custom_resource_definition_properties) continue to be supported

As of today, the only "special" annotation is `state-into-spec`. For this resource, we have determined that all fields that would support `state-into-spec: merge` can be retrieved from the `status.observedState`. So for LLM as a direct controller resource, the annotation will be ignored.

**Comment by acpana** [comment]
* [x] management-conflict-prevention-policy

This seems to be a TF based construct and would not apply to DCL based resources (which LLM is at the moment).

**Comment by acpana** [comment]
KCC System
* [x] Double check that the user agent is set as Kcc/controller-manager (consistent with other controllers) in order for usage telemetry to work

We set the KCCUserAgent at registration time in the manager:

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/593727199f4559c92f950b09611bc630f75934f2/pkg/controller/kccmanager/kccmanager.go#L139

**Comment by acpana** [comment]
Primarily via https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1772 and other work around using the GCP updateTime, we protect against:

* [x] Verify that mutable-but-unreadable fields don't cause (infinite) diffs

This is now being handled in the `logmetric_controller`: 
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/58f715454513f270363c3478c76b3227c1337038/pkg/controller/direct/logging/utils.go#L234-L237

* [x] Verify that any custom diffs from the DCL controller are reflected in the direct path

Insofar as backwards compat and testing tough scenarios, between the work to add the dynamic controller for LoggingLogMetric as a direct resource and the step/ scenario tests, I called these `testing` section done too.

**Comment by acpana** [comment]
* [ ]  unmanaging works

needs further discussion

the following were not added as labels

* [ ] mutable-but-unreadable-fields
using the GCP update time to avoid spurious updates
* [ ] supports-ssa
seems not needed anymore, see #1745 
* [ ] blueprint
actively removing code paths for this: #1830

**Comment by acpana** [comment]
The `enhancements` section will be made as its own issue.
